### ISSUE TITLE
isFromOldGeneration failures in 0.0.42 and 0.0.43

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1143]
I am dragging cards from 1 hand to another hand. When I begin dragging a card, I see this error:

```
'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 856 pos 12: 'isFromOldGeneration' is not true.
```

`adb logcat` shows that my card widget is on _generation 20 while  `Widget._currentGeneration` is also 20. The requirement is `_generation < Widget._currentGeneration`, so I think that either `_endSyncPhase` isn't being called enough or `_markAsFromCurrentGeneration` is being called too much.

I find lines 996 to 1001 of `widgets/framework.dart` to be suspicious. I think that the assert's comment is misleading. By resetting index to 0, if the sortedDirtyComponents wasn't empty, it looks like >=1 items will be built a second time. The reason is that the built components in sortedDirtyComponents aren't removed; instead the new dirty components are appended, the full list is re-sorted, and building restarts from the beginning.

@Hixie: The assertion that failed came from this pull request: https://github.com/domokit/sky_engine/commit/79ba8b9fcd0150ee06a8901fdba6168384f09376
If I use sky: 0.0.41 (and sky_engine: 0.0.18 and sky_services 0.0.18), which occurred before this code was submitted, moving cards around works again.

==========================================

I don't know if it's related, but upon dropping the card, I get another error:
```
'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 1358 pos 12: 'oldChild == null || child == oldChild || oldChild.parent == null' is not true.
```

**Comment by Hixie** [comment]
Yeah, I saw this earlier today too. I'm on it.

**Comment by abarth** [comment]
@Hixie Did you fix this in your patch today?

**Comment by Hixie** [comment]
Not yet.

**Comment by Hixie** [comment]
I think I've fixed this (though maybe by #1180 and #1175, which aren't yet checked in).

**Comment by afandria** [comment]
Still getting these problems with my app's drag and drop behavior. I noticed that a parent would sync its children (and do the current generation mark), but since the child is also dirty, it will build but fail the assert since it's already marked. (This occurs somewhat randomly since it looks like the build order depends on `_order`).

I see that the CLs are committed but not part of pub and would like to try it out. Can you revision a new pub package?

**Comment by abarth** [comment]
> Can you revision a new pub package?

Yep.  Will do.

**Comment by abarth** [comment]
Done.

**Comment by afandria** [comment]
Unfortunately, I'm still seeing the error upon dropping a child.

In here: https://github.com/flutter/engine/blob/d2a5a97fd5da5a19d51105feba4e32433f1dd902/sky/packages/sky/lib/src/widgets/framework.dart

This sets the dropped child to the current generation, even though it is dirty.
```
        if (newNode != null) {
          newNode.setParent(this);
          newNode._markAsFromCurrentGeneration();
        }
```

However, commenting out the mark or doing the following don't solve the problem:

```
        if (newNode != null) {
          newNode.setParent(this);
          if (newNode is Component)
            newNode._buildIfDirty();
          newNode._markAsFromCurrentGeneration();
          print("${newNode.hashCode} ${newNode._generation} SUSPICIOUS");
        }
```

Here's the long stack, in case it helps. The Card `360987942` is dropped onto a pile of other cards.
(_markAsFromCurrentGeneration was modified to print the hashCode and _generation number too.)

```
I/sky     (15309): Card(hashCode=360987942; mounted; gen-1})
I/sky     (15309): 360987942 68
I/sky     (15309): 360987942 68 SUSPICIOUS
I/sky     (15309): 487986899 68
I/sky     (15309): 307930029 68
I/sky     (15309): 509120578 68
I/sky     (15309): 48567078 68
I/sky     (15309): 49368335 68
I/sky     (15309): 979769412 68
I/sky     (15309): 1019462680 68
I/sky     (15309): 899642234 68
I/sky     (15309): 580089163 68
I/sky     (15309): 945425996 68
I/sky     (15309): 614353209 68
I/sky     (15309): 1033727217 68
I/sky     (15309): 547159883 68
I/sky     (15309): 680341980 68
I/sky     (15309): 360987942 68 FAILED
I/sky     (15309): ------------------------------------------------------------------------
I/sky     (15309): Exception caught while syncing children of Opacity(hashCode=655244199; mounted; never synced})
I/sky     (15309):   old child: null
I/sky     (15309):   new child: Card(hashCode=360987942; mounted})
I/sky     (15309): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 348 pos 12: 'isFromOldGeneration' is not true.
I/sky     (15309): Stack trace:
I/sky     (15309): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/sky     (15309): #1      Widget._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:348:12)
I/sky     (15309): #2      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:857:16)
I/sky     (15309): #3      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #4      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #5      Opacity.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:51:27)
I/sky     (15309): #6      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #7      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #8      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #9      Transform.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:178:27)
I/sky     (15309): #10     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #11     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #12     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:633:13)
I/sky     (15309): #13     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #14     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #15     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #16     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #17     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:633:13)
I/sky     (15309): #18     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #19     RenderObjectWrapper.syncChildren (http://localhost:9888/packages/sky/src/widgets/framework.dart:1327:18)
I/sky     (15309): #20     MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1493:7)
I/sky     (15309): #21     Flex.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:594:27)
I/sky     (15309): #22     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #23     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #24     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #25     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #26     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #27     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #28     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #29     DecoratedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:94:27)
I/sky     (15309): #30     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #31     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #32     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #33     SizedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:254:27)
I/sky     (15309): #34     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #35     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #36     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #37     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #38     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #39     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #40     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #41     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #42     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #43     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #44     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:871:5)
I/sky     (15309): #45     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1018:19)
I/sky     (15309): #46     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:884:7)
I/sky     (15309): #47     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1531:15)
I/sky     (15309): #48     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
I/sky     (15309): Build stack:
I/sky     (15309):   DragTarget<Card>(hashCode=876427864; mounted; gen-5; dirty; stateful})
I/sky     (15309):   Container(hashCode=475258815; mounted; never synced; dirty})
I/sky     (15309):   Draggable<Card>(hashCode=303135400; mounted; never synced; dirty; stateful})
I/sky     (15309): ------------------------------------------------------------------------
I/sky     (15309): ------------------------------------------------------------------------
I/sky     (15309): Exception caught while syncing children of Transform(hashCode=13413735; mounted; never synced})
I/sky     (15309):   old child: null
I/sky     (15309):   new child: Opacity(hashCode=655244199; not mounted; never synced})
I/sky     (15309): The null object does not have a getter 'parent'.
I/sky     (15309): 
I/sky     (15309): NoSuchMethodError: method not found: 'parent'
I/sky     (15309): Receiver: null
I/sky     (15309): Arguments: []
I/sky     (15309): Stack trace:
I/sky     (15309): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/sky     (15309): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/sky     (15309): #2      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1409:78)
I/sky     (15309): #3      Opacity.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:51:27)
I/sky     (15309): #4      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #5      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #6      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #7      Transform.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:178:27)
I/sky     (15309): #8      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #9      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #10     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:633:13)
I/sky     (15309): #11     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #12     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #13     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #14     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #15     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:633:13)
I/sky     (15309): #16     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #17     RenderObjectWrapper.syncChildren (http://localhost:9888/packages/sky/src/widgets/framework.dart:1327:18)
I/sky     (15309): #18     MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1493:7)
I/sky     (15309): #19     Flex.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:594:27)
I/sky     (15309): #20     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #21     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #22     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #23     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #24     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #25     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #26     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #27     DecoratedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:94:27)
I/sky     (15309): #28     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #29     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #30     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #31     SizedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:254:27)
I/sky     (15309): #32     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #33     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #34     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #35     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #36     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #37     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #38     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #39     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #40     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #41     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #42     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:871:5)
I/sky     (15309): #43     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1018:19)
I/sky     (15309): #44     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:884:7)
I/sky     (15309): #45     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1531:15)
I/sky     (15309): #46     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
I/sky     (15309): Build stack:
I/sky     (15309):   DragTarget<Card>(hashCode=876427864; mounted; gen-5; dirty; stateful})
I/sky     (15309):   Container(hashCode=475258815; mounted; never synced; dirty})
I/sky     (15309):   Draggable<Card>(hashCode=303135400; mounted; never synced; dirty; stateful})
I/sky     (15309): ------------------------------------------------------------------------
I/sky     (15309): ------------------------------------------------------------------------
I/sky     (15309): Exception caught while syncing children of Listener(hashCode=1001172244; mounted; never synced})
I/sky     (15309):   old child: null
I/sky     (15309):   new child: Transform(hashCode=13413735; not mounted; never synced})
I/sky     (15309): The null object does not have a getter 'parent'.
I/sky     (15309): 
I/sky     (15309): NoSuchMethodError: method not found: 'parent'
I/sky     (15309): Receiver: null
I/sky     (15309): Arguments: []
I/sky     (15309): Stack trace:
I/sky     (15309): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/sky     (15309): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/sky     (15309): #2      OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1409:78)
I/sky     (15309): #3      Transform.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:178:27)
I/sky     (15309): #4      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #5      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #6      TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:633:13)
I/sky     (15309): #7      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #8      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #9      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #10     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #11     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:633:13)
I/sky     (15309): #12     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #13     RenderObjectWrapper.syncChildren (http://localhost:9888/packages/sky/src/widgets/framework.dart:1327:18)
I/sky     (15309): #14     MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1493:7)
I/sky     (15309): #15     Flex.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:594:27)
I/sky     (15309): #16     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #17     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #18     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #19     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #20     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #21     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #22     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #23     DecoratedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:94:27)
I/sky     (15309): #24     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #25     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #26     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #27     SizedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:254:27)
I/sky     (15309): #28     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #29     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #30     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #31     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #32     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #33     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #34     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #35     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #36     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #37     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #38     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:871:5)
I/sky     (15309): #39     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1018:19)
I/sky     (15309): #40     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:884:7)
I/sky     (15309): #41     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1531:15)
I/sky     (15309): #42     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
I/sky     (15309): Build stack:
I/sky     (15309):   DragTarget<Card>(hashCode=876427864; mounted; gen-5; dirty; stateful})
I/sky     (15309):   Container(hashCode=475258815; mounted; never synced; dirty})
I/sky     (15309):   Draggable<Card>(hashCode=303135400; mounted; never synced; dirty; stateful})
I/sky     (15309): ------------------------------------------------------------------------
I/sky     (15309): 1001172244 68
I/sky     (15309): ------------------------------------------------------------------------
I/sky     (15309): Exception caught while syncing children of Draggable<Card>(hashCode=303135400; mounted; never synced; dirty; stateful})
I/sky     (15309):   old child: null
I/sky     (15309):   new child: Listener(hashCode=1001172244; not mounted; never synced})
I/sky     (15309): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 525 pos 14: 'newNode.renderObject is RenderObject' is not true.
I/sky     (15309): Stack trace:
I/sky     (15309): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/sky     (15309): #1      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:525:14)
I/sky     (15309): #2      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #3      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #4      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #5      TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:633:13)
I/sky     (15309): #6      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #7      RenderObjectWrapper.syncChildren (http://localhost:9888/packages/sky/src/widgets/framework.dart:1327:18)
I/sky     (15309): #8      MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1493:7)
I/sky     (15309): #9      Flex.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:594:27)
I/sky     (15309): #10     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #11     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #12     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #13     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #14     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #15     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #16     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #17     DecoratedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:94:27)
I/sky     (15309): #18     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #19     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #20     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #21     SizedBox.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:254:27)
I/sky     (15309): #22     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #23     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #24     OneChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1408:14)
I/sky     (15309): #25     Padding.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/basic.dart:196:27)
I/sky     (15309): #26     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1138:5)
I/sky     (15309): #27     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #28     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #29     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:524:15)
I/sky     (15309): #30     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:834:16)
I/sky     (15309): #31     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:935:16)
I/sky     (15309): #32     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:871:5)
I/sky     (15309): #33     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1018:19)
I/sky     (15309): #34     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:884:7)
I/sky     (15309): #35     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1531:15)
I/sky     (15309): #36     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
I/sky     (15309): Build stack:
I/sky     (15309):   DragTarget<Card>(hashCode=876427864; mounted; gen-5; dirty; stateful})
I/sky     (15309):   Container(hashCode=475258815; mounted; never synced; dirty})
I/sky     (15309):   Draggable<Card>(hashCode=303135400; mounted; never synced; dirty; stateful})
I/sky     (15309): ------------------------------------------------------------------------
```

**Comment by Hixie** [comment]
This should be fixed now.

**Comment by afandria** [comment]
Yes, thanks for writing the new framework!
