### ISSUE TITLE
Sky flickers in modroid on certain devices

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#36]
_From @tonygentilcore on July 7, 2015 17:59_

I have a private sky demo (can give repro instructions offline) that has severe UI flicker on a 2013 Nexus 7, moderate UI flicker on a OnePlus One, but is rock solid on an Android One (sprout).

Sometimes the flicker just flashes by itself and sometimes various components or pieces of components snap in or out of view upon touch input. I suspect we need to reduce a test case, but I'm not sure the best way to go about that. I also have no idea whether this repros in sky shell.

/cc @abarth 

_Copied from original issue: domokit/mojo#298_

**Comment by Hixie** [comment]
_From @abarth on July 7, 2015 20:56_

The next step here is to build a reduced test case of the flicker.

**Comment by Hixie** [comment]
_From @tonygentilcore on July 8, 2015 14:16_

Repros on @jimbeveridge 's Nexus 5 too. He's getting some GL OOM messages in the log that might be a clue.

**Comment by Hixie** [comment]
_From @jimbeveridge on July 8, 2015 14:33_

Here's a snip from the list of errors. Note the Out of Memory error buried in the list.

```
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
[ERROR:texture_manager.cc(1708)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D: 
[ERROR:gles2_cmd_decoder.cc(3432)] [GroupMarkerNotSet(crbug.com/242999)!:54BCCAA1]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
```

**Comment by Hixie** [comment]
_From @tonygentilcore on July 8, 2015 14:41_

By the way, this does seem like a recent regression (~1 week ago). I never noticed it on the FN based version of that UI (although so much has been changing that I definitely can't say this was introduced by our conversion to Widgets).

**Comment by Hixie** [comment]
_From @tonygentilcore on July 8, 2015 23:34_

@abarth and I confirmed this is specific to mojo shell (sky shell is fine) and readily reproduces via:
```
./mojo/tools/mojo_shell.py --sky sky/sdk/example/stocks/lib/main.dart --android
```

/cc @viettrungluu-cr @MitchRudominer

**Comment by Hixie** [comment]
_From @MitchRudominer on July 8, 2015 23:42_

Since @abarth is probably the person who best understands the relevant differences between Sky Shell and Mojo Shell, could he hazard a guess as to the layer of technology that might be a likely culprit?

**Comment by Hixie** [comment]
_From @abarth on July 9, 2015 2:16_

The difference is that Sky Shell has Skia talking directly to Android GL driver whereas Mojo Shell has Skia talking to a command buffer and the Surfaces service.  My guess is that there's some bad interaction between Skia and the command buffer, potentially something that causes a GPU resource leak.

**Comment by Hixie** [comment]
_From @tonygentilcore on July 9, 2015 2:47_

Sounds hairy. No one seems to have touched that code in many months. Is there anyone outside of @jamesr and @sky2 that stand a chance at debugging this? If not, should we consider coercing mojo to go down the same path as sky (at least temporarily until someone owns the surfaces service)?

/cc @qsr @chrismckillop

**Comment by Hixie** [comment]
_From @chrismckillop on July 9, 2015 3:4_

@iansf has been digging into the re-architecting of this part of the system.  Perhaps he can debug it a little in the short term to see if can't plaster over the issue until the bigger work is done?

**Comment by Hixie** [comment]
_From @iansf on July 9, 2015 16:43_

I agree this seems like something I might be able to figure out.  Tony, do
you want to get me set up on your app sometime today so that I can dive
into it?

**Comment by Hixie** [comment]
_From @tonygentilcore on July 9, 2015 17:18_

Thanks! No need to set that up. See repro instructions in https://github.com/domokit/mojo/issues/298#issuecomment-119759384 .

**Comment by Hixie** [comment]
_From @iansf on July 9, 2015 18:14_

Cool -- I have the repro on my HTC 1+.  Sadly, the driver doesn't log any opengl errors for me, so I will try to get my hands on a Nexus 5.

**Comment by Hixie** [comment]
_From @iansf on July 14, 2015 0:25_

Blocked by #318

**Comment by Hixie** [comment]
_From @iansf on July 15, 2015 23:46_

 - I am able to reproduce the graphical errors on a Nexus 5, but I do not get any OpenGL errors being logged on that device.
 - I figured out how to get the Android Monitor GLTracer to work with mojo apps approximately, but for some reason it only records the egl commands, and not the opengl commands (two eglMakeCurrent calls and an eglSwapBuffers call), even though it successfully records the framebuffer contents when they get into a broken state.
 - I turned on SK_DEBUG, GR_GL_CHECK_ERROR, and GR_GL_LOG_CALLS in Skia to see what would happen (one at a time and together).  In all three cases, there are no errors reported, and the graphical corruption stops happening.  This makes me think there is a timing problem with talking to the graphics driver, since the app runs so slowly in those modes that inkwells usually don't even show up.
 - I have not found a working way to attach gdb to a sky app launched with mojo_shell -- even manually calling the adb shell commands gives me problematic errors that I haven't yet found a way around.  At this point, though, I'm not sure that gdb would help me diagnose this problem.

**TL;DR**: I am blocked on this bug.  We need better tools for dealing with graphical corruption issues on Android (or if we have them already, I would love to know about them).

If someone knows how to get a proper GLTrace out of Monitor for mojo apps, that would be a huge help.  @cdotstout -- any experience with this?

**Comment by Hixie** [comment]
_From @abarth on July 16, 2015 3:49_

@iansf There's a way to make the command buffer log all the GL commands it touches.  I'd look around in //gpu/command_buffer for something that looks like logging.

**Comment by Hixie** [comment]
_From @cdotstout on July 16, 2015 4:57_

I don't have experience getting gl traces from mojo apps.  

Have you tried the qualcomm gpu profiler?

https://developer.qualcomm.com/software/adreno-gpu-profiler

**Comment by tonygentilcore** [comment]
@gabeschine found that removing the floating action button fixes the flicker. It has a clip and a drop shadow. Not sure if that provides any clues.

Also, you mentioned it may not help, but gdb support should be working in mojo devtools now.

**Comment by gabeschine** [comment]
Just did some digging with Ian - we found this only happens if the floatingActionButton is a circle.

Commenting out sky_sdk/sky/lib/painting/box_painter.dart:270:

270           canvas.drawCircle(center, radius, _backgroundPaint);                                                                                  

causes the problem to go away.

**Comment by MitchRudominer** [comment]
Could be completely unrelated but your mention of a circle reminds me of
https://github.com/domokit/mojo/issues/135.

There we suspected that the difference between a circle and a square had to do with the use of anti-aliasing in skia.

**Comment by iansf** [comment]
An update on the status of this.  I have found a work-around which fixes the issue and indicates what the root cause of the problem is.

**The Workaround:**
In ```ui/gl/gl_context_egl.cc```, add the following line inside of ```GLContextEGL::MakeCurrent```, around line 114:
```
if (eglGetCurrentContext() != EGL_NO_CONTEXT) glFinish();
```

**What This Means:**
We appear to have a synchronization problem in our command buffer implementation that is causing commands go to the incorrect EGL context.  Calling ```glFinish()``` right before changing contexts forces the driver to wait for queued commands to complete.

I'm digging into this in ```gpu/command_buffer/client/gles2_implementation.cc``` right now.  Hopefully the next update will be an actual fix, but feel free to use the workaround locally in the mean time.

**Comment by tonygentilcore** [comment]
Verified the workaround does indeed address the flicker. Looking forward to the fix :)

**Comment by kulakowski** [comment]
For what it's worth, I can trigger a couple different crashes via spamming scrolls that flicker.

One is just an OOM fatal in Dart [here](https://github.com/dart-lang/sdk/blob/master/runtime/vm/scavenger.cc#L469).

The other is a SIGILL on an address like 0x975a8e84, though I haven't managed to get any more context than that yet.

**Comment by iansf** [comment]
Which app and device can you do that on?  Does it still happen if you put the glFinish() line in?  I'm happy to check the work-around if you want.

**Comment by kulakowski** [comment]
The same demo Tony was working on, on a OnePlus One.

I can reproduce for you tomorrow. I don't think I had the glFinish() line in.

**Comment by tonygentilcore** [comment]
@jamesr or @viettrungluu-cr might also have ideas on the findings in https://github.com/domokit/sky_engine/issues/36#issuecomment-122970122

**Comment by tonygentilcore** [comment]
@iansf are you still actively working on this or would it be good to hand off?

**Comment by iansf** [comment]
Thanks for pinging this.  @jamesr and I were planning on meeting up last week to look at this, but that didn't happen.  I'll meet with him this week to push this forward.

**Comment by tonygentilcore** [comment]
After a while of flicker, I got a new error. Not sure if it helps.
```
[ERROR:gles2_cmd_decoder.cc(10351)] Context lost because SwapBuffers failed.
[ERROR:gles2_cmd_decoder.cc(4158)] Error: 5 for Command kSwapBuffers
```

I also tried to reduce the repro a bit (from the current state of it repros when you add a `FloatingActionButton`). Turns out that removing either the drop shadow or the circle clip fixes it. It's the presence of both that is needed to trigger the flicker.

Is there much more I could do to help out? Perhaps diffing up some code/changes vs chromium? Or maybe someone can teach me how to see the difference in skpictures for the various cases?

**Comment by tonygentilcore** [comment]
Also tried rolling skia to the chrome m45 branch, but no dice.

**Comment by jamesr** [comment]
Hmm, given that enabling context virtualization which would have serialized all command onto one egl context didn't resolve the flicker I'm a little dubious that the flush is really the right answer. Please let me know if you still see badness.

@iansf maybe the next thing to do is to try to capture a bad frame sequence with context virtualization enabled in monitor and try to reproduce in a standalone app that talks to egl directly. Alternately, compare the gl stream to what sky shell emits.

**Comment by tonygentilcore** [comment]
Thanks James! That patch improved things a great deal. Several UIs used to flicker and they're all solved except that action button example. That should still be fixed, but things are usable now.

**Comment by jamesr** [comment]
That's good to hear.  I don't think the bug is really completely fixed, but if you and yours are able to make progress without getting headaches that's definitely an improvement.  This has a very minor perf impact as well (1 possibly unnecessarily glFlush per frame).

**Comment by turu** [comment]
What is the current status of this issue? Is anyone working on it? I'm asking, because it still severely affects any code that uses FloatingActionButtons extensively. I would prefer to avoid having to design around this bug.

**Comment by iansf** [comment]
I would recommend that we commit the workaround that I originally found if this is blocking you.  It seems to completely fix the issue, at the expense of two glFinishes per frame.  That being said, I would defer to @jamesr's opinion on this, since he's much more deeply involved with the graphics stack than I am.

**Comment by Hixie** [comment]
IMHO we shouldn't check in workarounds. We can't afford the technical debt. It just ends up costing us more later.

**Comment by cdotstout** [comment]
I'll try investigating further. I haven't been working with sky though so can someone post up-to-date repro steps?

**Comment by tonygentilcore** [comment]
Hopefully @ppiet or @qsr can fill in repro steps. I tried for a while but wasn't able to come up with a way to run a sky app in mojo in such a way that I could describe in a handful of repro steps. I could point you at a one-liner to repro this in a private repo if that's any help.

**Comment by cdotstout** [comment]
A one-liner sounds just fine to me :)

**Comment by turu** [comment]
@cdotstout @qsr @iansf 
In case anyone prefers a self-contained repro, here it is:
```Dart
import 'package:sky/theme/colors.dart';
import 'package:sky/widgets/basic.dart';
import 'package:sky/widgets.dart';

class FlickerApp extends App {
  @override
  Widget build() {
    return new Container(
        decoration: new BoxDecoration(backgroundColor: RedAccent[700]),
        child: new FloatingActionButton(
            child: new Icon(type: "action/account_circle", size: 24)));
  }
}
```
Just click on the big button to see the failure mode (\*\*Seizure Warning!** :wink: ).

**Comment by cdotstout** [comment]
Flicker should be resolved:
https://codereview.chromium.org/1348283004/

The glFlush that was added can likely now be removed.

**Comment by abarth** [comment]
\o/

**Comment by turu** [comment]
The flicker seems fixed for me. Is anyone else still experiencing it?

**Comment by abarth** [comment]
I'll take that as this issue being fixed.
